### ISSUE TITLE
Anyone want to take this over?

### ISSUE THREAD

**Issue by peter-edge** [peter-edge/smartystreets_ruby#6]
I've moved on from this project more than a year ago now, but I know that there are a bunch of people who still use it - if anyone would be interested in being the primary maintainer of this, and can show they use it/are actively updating it, I'm happy to deprecate this project and link everything over to their fork, and give them ownership of the gem.

**Comment by jayelkaake** [comment]
I'd love to take it over if the offer is still up.

**Comment by paulwalker** [comment]
Given that his branch has correct URLs for zipcode search and this current branch is broken, because it does not, can we move this forward?

**Comment by peter-edge** [comment]
@jayelkaake @paulwalker ya who wants it?

**Comment by jayelkaake** [comment]
*raises hand* :)

**Comment by peter-edge** [comment]
What email should I add for owners for the gem? I would propose this:

- Fork the repository
- I'll update the readme to point to yours
- I'll add you as an owner on the gem (once you give me an email to add)

**Comment by peter-edge** [comment]
Or just for my own sanity, either update your fork to the latest commit here, or delete it and re-fork it https://github.com/jayelkaake/smartystreets_ruby
